// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjcEAi5Nm80ZR1fCldyEyndZ8Qgi7iMiw',
    appId: '1:284144994460:web:37b6b8c75907b864938559',
    messagingSenderId: '284144994460',
    projectId: 'chat-app-34e9f',
    authDomain: 'chat-app-34e9f.firebaseapp.com',
    storageBucket: 'chat-app-34e9f.appspot.com',
    measurementId: 'G-19M33LH5SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpkaafWmSbFtKlJAqTmqFZt1fHj6wYNKc',
    appId: '1:284144994460:android:9d49b14dff673ccf938559',
    messagingSenderId: '284144994460',
    projectId: 'chat-app-34e9f',
    storageBucket: 'chat-app-34e9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7HO_hgARfKY9lUUpAIra_iWGrIWlQBQY',
    appId: '1:284144994460:ios:4f18ad27765d0a96938559',
    messagingSenderId: '284144994460',
    projectId: 'chat-app-34e9f',
    storageBucket: 'chat-app-34e9f.appspot.com',
    iosClientId: '284144994460-0g3v8tmvl3uef1ff6nf0b6iie2080vdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7HO_hgARfKY9lUUpAIra_iWGrIWlQBQY',
    appId: '1:284144994460:ios:6cc399ac19a0c10f938559',
    messagingSenderId: '284144994460',
    projectId: 'chat-app-34e9f',
    storageBucket: 'chat-app-34e9f.appspot.com',
    iosClientId: '284144994460-k8sk2fjtbs0eo9ck8bl427ibusol4gaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
